### ISSUE TITLE
Redesign how assert methods are defined

### ISSUE THREAD

**Issue by philzon** [philzon/helm-assert#17]
**Current**

Asserts are defined using specified keys that performs specific operations, supported by arguments being passed in from its child keys:

```yaml
# Returns true if key 'foo.bar' has value of 'baz'
- equal:
    key: foo.bar
    value: baz
```

**Proposal**

Proposal is to **not** have a specific key determine the type of assert being used. All keys shall be exposed and executed if used.

```yaml
- key: foo.bar # (Mandatory) checks if key exist, and gets the key's value
  contains: ba # (Optional) check if key's value contains 'ba'
  value: baz    # (Optional) check if key's value is 'baz'
  ...
```

A single assert structure has all keys which are executed in a particular order. This minimizes the amount of creating separate assert methods.

**Rationale**

The **current** implementation has created unnecessary boilerplate to support different assert methods, all using separate structures.

All assert objects can exist in a single assert due to how it is structured statically, and all of them can work at the same time, although override each other if their mandatory parameters are defined. This can of course be mitigated by preventing multiple asserts from being executed, but, depending the order of execution, will result in asserts having a higher precedence.
