### ISSUE TITLE
Unable to assert keys containing dots

### ISSUE THREAD

**Issue by philzon** [philzon/helm-assert#7]
The following YAML, and its key `metadata.annotations.foo.bar`, will always return `nil` on asserts.

```yaml
metadata:
  annotations:
    foo.bar: test
```
