### ISSUE TITLE
Unable to render if NOTES.txt contains any YAML structure

### ISSUE THREAD

**Issue by philzon** [philzon/helm-assert#8]
A simple `NOTES.txt` file could contain:

```yaml
This is a test

foo:
  bar: baz
```

This is enough for the tool to crash. `NOTES.txt` should not be included as a rendered manifest.
